# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance_estimated <- function(alignment_sample_matrix, n_align_scalar, n_sample_scalar, errorrates_estimated_aligned_matrix) {
    .Call('_Distanced_distance_estimated', PACKAGE = 'Distanced', alignment_sample_matrix, n_align_scalar, n_sample_scalar, errorrates_estimated_aligned_matrix)
}

n_shared_indels <- function(alignment_sample_matrix, alignment_reference_matrix, n_sample_scalar, n_align_scalar) {
    .Call('_Distanced_n_shared_indels', PACKAGE = 'Distanced', alignment_sample_matrix, alignment_reference_matrix, n_sample_scalar, n_align_scalar)
}

