// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distance_estimated
NumericMatrix distance_estimated(CharacterMatrix alignment_sample_matrix, int n_align_scalar, int n_sample_scalar, NumericMatrix errorrates_estimated_aligned_matrix);
RcppExport SEXP _Distanced_distance_estimated(SEXP alignment_sample_matrixSEXP, SEXP n_align_scalarSEXP, SEXP n_sample_scalarSEXP, SEXP errorrates_estimated_aligned_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type alignment_sample_matrix(alignment_sample_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_align_scalar(n_align_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample_scalar(n_sample_scalarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type errorrates_estimated_aligned_matrix(errorrates_estimated_aligned_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_estimated(alignment_sample_matrix, n_align_scalar, n_sample_scalar, errorrates_estimated_aligned_matrix));
    return rcpp_result_gen;
END_RCPP
}
// n_shared_indels
NumericVector n_shared_indels(CharacterMatrix alignment_sample_matrix, CharacterMatrix alignment_reference_matrix, int n_sample_scalar, int n_align_scalar);
RcppExport SEXP _Distanced_n_shared_indels(SEXP alignment_sample_matrixSEXP, SEXP alignment_reference_matrixSEXP, SEXP n_sample_scalarSEXP, SEXP n_align_scalarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterMatrix >::type alignment_sample_matrix(alignment_sample_matrixSEXP);
    Rcpp::traits::input_parameter< CharacterMatrix >::type alignment_reference_matrix(alignment_reference_matrixSEXP);
    Rcpp::traits::input_parameter< int >::type n_sample_scalar(n_sample_scalarSEXP);
    Rcpp::traits::input_parameter< int >::type n_align_scalar(n_align_scalarSEXP);
    rcpp_result_gen = Rcpp::wrap(n_shared_indels(alignment_sample_matrix, alignment_reference_matrix, n_sample_scalar, n_align_scalar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Distanced_distance_estimated", (DL_FUNC) &_Distanced_distance_estimated, 4},
    {"_Distanced_n_shared_indels", (DL_FUNC) &_Distanced_n_shared_indels, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Distanced(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
